"""Add source links to HTML generated by ``render_report.py``."""

from __future__ import annotations

import re


SOURCE_ID = r"S\d{2,}"
SKIP_ELEMENTS = {"a", "code", "pre", "script", "style"}
SOURCE_ROW = re.compile(
    rf"<tr\b(?=[^>]*\bid\s*=\s*['\"]src-{SOURCE_ID}['\"])[^>]*>",
    flags=re.IGNORECASE,
)


def linkify_html(html: str) -> tuple[str, int, int]:
    """Link ``[Sxx]`` citations and return HTML, links added, and ledger rows."""

    row_pattern = re.compile(
        rf"<tr(?P<attrs>[^>]*)>\s*"
        rf"(?P<cells><td(?:\s[^>]*)?>\s*(?P<sid>{SOURCE_ID})\s*</td>.*?</tr>)",
        flags=re.IGNORECASE | re.DOTALL,
    )

    def add_anchor(match: re.Match[str]) -> str:
        attrs = match.group("attrs")
        if re.search(r"\bid\s*=", attrs, flags=re.IGNORECASE):
            return match.group(0)
        return f'<tr{attrs} id="src-{match.group("sid")}">{match.group("cells")}'

    html = row_pattern.sub(add_anchor, html)
    url_map: dict[str, str] = {}
    for row in re.finditer(r"<tr\b([^>]*)>(.*?)</tr>", html, re.IGNORECASE | re.DOTALL):
        anchor = re.search(
            rf"\bid\s*=\s*['\"]src-({SOURCE_ID})['\"]",
            row.group(1),
            flags=re.IGNORECASE,
        )
        if not anchor:
            continue
        href = re.search(
            r"href\s*=\s*(['\"])(https?://.*?)\1",
            row.group(2),
            flags=re.IGNORECASE | re.DOTALL,
        )
        bare = re.search(r'(?<!["\'=])(https?://[^\s<)"\']+)', row.group(2))
        url = href.group(2) if href else bare.group(1) if bare else ""
        if url:
            url_map[anchor.group(1)] = url.rstrip(".,;。")

    def citation(match: re.Match[str]) -> str:
        sid = match.group(1)
        if sid in url_map:
            return (
                f'<a href="{url_map[sid]}" target="_blank" '
                f'rel="noopener noreferrer" class="src-link">[{sid}]</a>'
            )
        return f'<a href="#src-{sid}" class="src-link">[{sid}]</a>'

    output: list[str] = []
    in_ledger_row = False
    skip_depth = 0
    n_links = 0
    for part in re.split(r"(<[^>]+>)", html):
        if not part.startswith("<"):
            if in_ledger_row or skip_depth:
                output.append(part)
            else:
                linked, count = re.subn(rf"\[({SOURCE_ID})\]", citation, part)
                output.append(linked)
                n_links += count
            continue

        tag = re.match(r"<\s*(/?)\s*([a-z0-9]+)", part, flags=re.IGNORECASE)
        if tag:
            closing, name = bool(tag.group(1)), tag.group(2).lower()
            if name == "tr":
                in_ledger_row = False if closing else bool(SOURCE_ROW.match(part))
            if name in SKIP_ELEMENTS:
                if closing:
                    skip_depth = max(0, skip_depth - 1)
                elif not part.rstrip().endswith("/>"):
                    skip_depth += 1
        output.append(part)

    return "".join(output), n_links, len(SOURCE_ROW.findall(html))
